# Generated by Django 4.1.2 on 2022-10-07 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('blacks_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balcks', to=settings.AUTH_USER_MODEL)),
                ('whites_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen_code', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='api.match')),
            ],
        ),
    ]
