services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/backend/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    build:
      "context": .
      platforms:
        - "linux/amd64"
    restart: no
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run python3 manage.py makemigrations api &&
          poetry run python3 manage.py migrate api &&
          poetry run python3 manage.py makemigrations &&
          poetry run python3 manage.py migrate &&
          poetry run python3 manage.py collectstatic &&
          poetry run daphne backend.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - .:/app
      - static_volume:/backend/static
    depends_on:
      - db
  db:
    container_name: core_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
